backbone: resnet34
architecture: FPN
classes: 1
activation: sigmoid
encoder_weights: imagenet
shape: [384, 384, 3]

augmentation:
 Fliplr: 0.5
 Flipud: 0.5
optimizer: Adam
batch: 8
metrics:
  - binary_accuracy
primary_metric: val_binary_accuracy
primary_metric_mode: auto
freeze_encoder: true
callbacks:
  EarlyStopping:
    patience: 15
    monitor: val_binary_accuracy
    verbose: 1
  ReduceLROnPlateau:
    patience: 10
    factor: 0.1
    monitor: val_binary_accuracy
    mode: auto
    cooldown: 5
    verbose: 1
loss: binary_crossentropy
stages:
  - #loss: mse
    #lr: 0.4
    epochs: 3
    negatives: none
  - unfreeze_encoder: true
    #lr: 0.1
    loss: binary_crossentropy
    epochs: 1000
    negatives: none