backbone: mobilenetv2
architecture: DeepLabV3
augmentation:
 Fliplr: 0.5
classes: 1
activation: sigmoid
encoder_weights: pascal_voc
shape: [320, 320, 3]
optimizer: Adam
batch: 16
metrics:
  - binary_accuracy
primary_metric: val_binary_accuracy
callbacks:
  EarlyStopping:
    patience: 15
    monitor: val_binary_accuracy
    verbose: 1
  ReduceLROnPlateau:
    patience: 4
    factor: 0.5
    monitor: val_binary_accuracy
    mode: auto
    cooldown: 5
    verbose: 1
loss: binary_crossentropy
stages:
  - epochs: 100
    negatives: real